apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: myapp
data:
  nginx.conf: |
    user nginx nginx;
    worker_processes 1;

    error_log /dev/stdout notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      #gzip  on;

      upstream app {
        server localhost:3000 fail_timeout=0;
      }

      server {
        listen 80;
        server_name example.com;
        root /app/public;
        try_files $uri/index.html $uri @app;

        location @app {
            proxy_pass http://app;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
        }

        error_page 500 502 503 504 /500.html;
        client_max_body_size 4G;
        keepalive_timeout 10;
      }
    }
